### ISSUE TITLE
 Cannot call method 'search' of undefined

### ISSUE THREAD

**Issue by adeshpandey** [meteorbigdata/elasticsearch#7]
Hi,
I have recently installed this package to implement elastic search on one of my meteor projects but when I have tried to call search method i have found the following error, which might be cause due to lack of the proper documentation:

Exception while invoking method 'search' TypeError: Cannot call method 'search' of undefined
I20150304-18:12:42.881(5.5)?   at [object Object].Meteor.methods.search (/home/adesh/meteor_apps/new_app/.meteor/local/build/programs/server/packages/bigdata_elasticsearch.js:260:8)
I20150304-18:12:42.881(5.5)?   at maybeAuditArgumentChecks (/home/adesh/meteor_apps/new_app/.meteor/local/build/programs/server/packages/ddp.js:2445:12)
I20150304-18:12:42.882(5.5)?   at /home/adesh/meteor_apps/new_app/.meteor/local/build/programs/server/packages/ddp.js:1494:20
I20150304-18:12:42.882(5.5)?   at [object Object]._.extend.withValue (/home/adesh/meteor_apps/new_app/.meteor/local/build/programs/server/packages/meteor.js:1000:17)
I20150304-18:12:42.882(5.5)?   at /home/adesh/meteor_apps/new_app/.meteor/local/build/programs/server/packages/ddp.js:1493:41
I20150304-18:12:42.882(5.5)?   at [object Object]._.extend.withValue (/home/adesh/meteor_apps/new_app/.meteor/local/build/programs/server/packages/meteor.js:1000:17)
I20150304-18:12:42.882(5.5)?   at [object Object]._.extend.protocol_handlers.method (/home/adesh/meteor_apps/new_app/.meteor/local/build/programs/server/packages/ddp.js:1492:51)
I20150304-18:12:42.882(5.5)?   at /home/adesh/meteor_apps/new_app/.meteor/local/build/programs/server/packages/ddp.js:1392:43

**Comment by andrewreedy** [comment]
Can you show me the code you are using to call the method.
